# Generated by Django 4.0.3 on 2022-03-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBrowser', '0002_fooditems_farmtofork_alter_fooditems_gluten_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='id',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='item_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
