# Generated by Django 4.0.3 on 2022-03-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodBrowser', '0003_remove_fooditems_id_fooditems_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
